### ISSUE TITLE
Output style nested, compact not working

### ISSUE THREAD

**Issue by kartofelek007** [jedfoster/SassMeister#211]
Output style nested and compact not working

https://www.youtube.com/watch?v=Ew5WimmALk8&feature=youtu.be

**Comment by jedfoster** [comment]
So, it turns out that dart-sass, the canonical Sass implementation and the default on sassmeister.com, no longer supports nested or compact CSS output. https://github.com/sass/dart-sass/issues/442

For now, libsass and Ruby Sass still support those output styles, so what I am going to do is remove nested and compact as options when the selected compiler is any version of dart-sass. Not ideal, but seems to me the best solution.

**Comment by jedfoster** [comment]
And... deployed.
