### ISSUE TITLE
Is it possible to use your api?

### ISSUE THREAD

**Issue by askucher** [jedfoster/SassMeister#56]
http://sassmeister.com/compile

**Comment by dwjohnston** [comment]
Just for FWIW - I'm currently looking for a solution to dynamically compile sass in a browser, which is how I came accross this. 

Been looking at sass.js [but due to an issue with that](https://github.com/medialize/sass.js/issues/136), I'm looking at creating a 'compile the sass' API endpoint as a workaround. 

I'd be happy to drop a donation/subscription if it saves me a day's work.

**Comment by dwjohnston** [comment]
Hmmm, possibly this? https://github.com/mendix/sassaas-compiler

**Comment by jedfoster** [comment]
The compiler service itself could be as simple as this: 

```javascript
var compile = function(req, res) {
  var stats = {};
  var css = nodeSass.render({
    data: req.body.compiler.sass + ' ',
    outputStyle: req.body.compiler.outputStyle,
    stats: stats,
    success: function(css) {
      res.json({
        compiler: {
          css: css,
          stats: stats
        }
      });
    },
    error: function(error) {
      res.status(500).send(error);
    }
  });
};
app.post('/compile', compile);
```

See https://gitlab.com/jedfoster/bad-grizzly/-/blob/master/app/index.js. 

That's old code and the current SassMeister API's compiler service is a bit more complex, but mostly because of the extensions that SassMeister provides. Parsing/embedding dependency frontmatter is the bulk of the service's code.

**Comment by dwjohnston** [comment]
^Alright cool thanks. 

I've created a working minimal API here: 

https://github.com/dwjohnston/sass-compiler-api
